version: '3.3'

services:
  database:
    image: 'postgres:13.3'
    environment:
      POSTGRES_DB: filebin-data
      POSTGRES_USER: filebin
      POSTGRES_PASSWORD: test123
    networks:
      - filebin-network
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/

  service:
    build:
      context: .
      dockerfile: FileBin.Server/Dockerfile
    environment:
      Authorization__Username: username
      Authorization__Password: password
      Database: Host=database; Database=filebin-data; Port=5432; Username=filebin; Password=test123
    networks:
      - filebin-network
    ports:
      - "8080:80"

networks:
  filebin-network:

volumes:
  database-data:
