version: '3.3'

services:
  database:
    image: 'postgres:13.3'
    environment:
      POSTGRES_DB: filebin-data
      POSTGRES_USER: filebin
      POSTGRES_PASSWORD: test123
    networks:
      - filebin-network
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  service:
    build:
      context: .
      dockerfile: FileBin.Server/Dockerfile
    environment:
      Authorization__AuthEndpoint: https://id.corsac.nl/application/o/authorize/
      Authorization__TokenEndpoint: https://id.corsac.nl/application/o/token/
      Authorization__UserEndpoint: https://id.corsac.nl/application/o/userinfo/
      Authorization__ClientId: 2ed884d66f35e95bb21b3b24d5d8bb61235561a1
      Authorization__ClientSecret: 989261d6-5324-4ec2-b27b-4d2a12d4a6ce
      Authorization__Scopes__0: filebin.access
      Authorization__Scopes__1: filebin.admin
      Authorization__UserRole: FileBin User
      Authorization__AdminRole: FileBin Admin
      Database: Host=database; Database=filebin-data; Port=5432; Username=filebin; Password=test123
    networks:
      - filebin-network
    ports:
      - "8080:80"

networks:
  filebin-network:

volumes:
  database-data:
